trigger:
  branches:
    include:
      - rg
      - main
      - release/*

resources:
  repositories:
    # - repository: templates
    #   type: git
    #   project: 'Pipelines'
    #   name: devops-templates
    #   ref: 'rg'
    - repository: templates
      type: github
      endpoint: 'futurecodeit'
      name: 'futurecodeit/devops-templates'
      ref: 'rg'

stages:
  - template: infra-pipeline-templates/terraform/azure-pipeline.yml@templates